[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-driver"
]

[phases.install]
cmds = ["npm install --omit=dev"]

[start]
cmd = "node src/bot.js"

[variables]
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
